In [2]:
import numpy as np

In [5]:
lst = [1,2,3]
lst

[1, 2, 3]

In [7]:
np.array(lst)

array([1, 2, 3])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
n

AttributeError: module 'numpy' has no attribute 'twos'