In [2]:
import numpy as np

In [3]:
lst = [1,2,3]
lst

[1, 2, 3]

In [4]:
np.array(lst)

array([1, 2, 3])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [9]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr[1:,:2]

array([[40, 50],
       [70, 80]])

In [11]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2 = np.arange(50).reshape(5,10)

In [13]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
arr2[1,2:8]

array([12, 13, 14, 15, 16, 17])

In [15]:
arr2[3,:2]

array([30, 31])

In [17]:
import pandas as pd

In [18]:
lst = [10,20,30]
label = ["ph","us","jp"]


In [21]:
pd.Series(lst, label)

ph    10
us    20
jp    30
dtype: int64